export const packege = () => [
  {
    name: "Package 1",
    quota: "100 GB",
    price: "10.000 LYD",
    duration: "1 month",
    speedupLoading: "6 MB",
    speedupDownload: "6 MB",
  },
  {
    name: "Package 2",
    quota: "100 GB",
    price: "10.000 LYD",
    duration: "1 month",
    speedupLoading: "6 MB",
    speedupDownload: "6 MB",
  },
  {
    name: "Package 3",
    quota: "Unlimited",
    price: "10.000 LYD",
    duration: "1 month",
    speedupLoading: "6 MB",
    speedupDownload: "6 MB",
  },
  {
    name: "Package 4",
    quota: "100 GB",
    price: "10.000 LYD",
    duration: "1 month",
    speedupLoading: "6 MB",
    speedupDownload: "6 MB",
  },
  {
    name: "Package 5",
    quota: "100 GB",
    price: "10.000 LYD",
    duration: "1 month",
    speedupLoading: "6 MB",
    speedupDownload: "6 MB",
  },
  {
    name: "Package 6",
    quota: "100 GB",
    price: "10.000 LYD",
    duration: "1 month",
    speedupLoading: "6 MB",
    speedupDownload: "6 MB",
  },
];
